import base64

import pytest


@pytest.fixture(scope="module")
def favicon_data_48():
    """48x48 white PNG."""
    return base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAIAAADYYG7QAAAASElEQVR4nO3OoQHAIBAAsdL9d3485iSI"
        "ZIKsmfle8t8OnISKUBEqQkWoCBWhIlSEilARKkJFqAgVoSJUhIpQESpCRagIFaGyAXGwA118GEzeAAAA"
        "AElFTkSuQmCC"
    )


@pytest.fixture(scope="module")
def favicon_data_96():
    """96x96 white PNG."""
    return base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAIAAABt+uBvAAAA1ElEQVR4nO3QwQ3AIBDAsNL9dz4mQHnC"
        "w54gypqZj7P/dsDrDAoGBYOCQcGgYFAwKBgUDAoGBYOCQcGgYFAwKBgUDAoGBYOCQcGgYFAwKBgUDAoG"
        "BYOCQcGgYFAwKBgUDAoGBYOCQcGgYFAwKBgUDAoGBYOCQcGgYFAwKBgUDAoGBYOCQcGgYFAwKBgUDAoG"
        "BYOCQcGgYFAwKBgUDAoGBYOCQcGgYFAwKBgUDAoGBYOCQcGgYFAwKBgUDAoGBYOCQcGgYFAwKBgUDAoG"
        "BYOCQcGgYFDY+poDvQAivBYAAAAASUVORK5CYII="
    )


@pytest.fixture(scope="module")
def favicon_data_64_32():
    """64x32 white PNG."""
    return base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAIAAAAt/+nTAAAAQElEQVR4nO3PQQ0AIBDAMMC/50MEj4Zk"
        "VbDtmVk/OzrgVQNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oD2gUyKwM953EnbgAAAABJRU5ErkJg"
        "gg=="
    )


@pytest.fixture(scope="module")
def favicon_data_128_64():
    """128x64 white PNG."""
    return base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAIAAAABACAIAAABdtOgoAAAApUlEQVR4nO3RQREAIAzAMMC/501GHjQK"
        "etc7MyfO0wG/awDWAKwBWAOwBmANwBqANQBrANYArAFYA7AGYA3AGoA1AGsA1gCsAVgDsAZgDcAagDUA"
        "awDWAKwBWAOwBmANwBqANQBrANYArAFYA7AGYA3AGoA1AGsA1gCsAVgDsAZgDcAagDUAawDWAKwBWAOw"
        "BmANwBqANQBrANYArAFYA7AGYA3AFhvOA32iFHl+AAAAAElFTkSuQmCC"
    )


@pytest.fixture(scope="module")
def favicon_data_64_128():
    """64x128 white PNG."""
    return base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAEAAAACACAIAAAA04/g9AAAAoElEQVR4nO3PQQ0AIBDAMMC/50MEj4Zk"
        "VbDtmVk/OzrgVQNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNa"
        "A1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNa"
        "A1oDWgNaA1oDWgNaA1oD2gUMxQP9ijHcFQAAAABJRU5ErkJggg=="
    )


@pytest.fixture(scope="module")
def favicon_data_144():
    """144x144 white PNG (for 48x48@3)."""
    return base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAIAAABoJHXvAAABY0lEQVR4nO3RwQkAIBDAMHX/nc8ZfEkh"
        "maDQPTOLjvM7gDeGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgW"
        "Y1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGG"
        "xRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iM"
        "YTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgW"
        "Y1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGGxRgWY1iMYTGG"
        "xRgWY1iMYTGGxRgWY1iMYTGGxRgWcwH2lQQd7GyBMgAAAABJRU5ErkJggg=="
    )


@pytest.fixture(scope="module")
def favicon_data_192():
    """192x192 white PNG (for 96x96@2)."""
    return base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAIAAADdvvtQAAAB6ElEQVR4nO3SwQ3AIBDAsNL9dz52IA+E"
        "ZE+QR9bMfHDqvx3A2wxEYiASA5EYiMRAJAYiMRCJgUgMRGIgEgORGIjEQCQGIjEQiYFIDERiIBIDkRiI"
        "xEAkBiIxEImBSAxEYiASA5EYiMRAJAYiMRCJgUgMRGIgEgORGIjEQCQGIjEQiYFIDERiIBIDkRiIxEAk"
        "BiIxEImBSAxEYiASA5EYiMRAJAYiMRCJgUgMRGIgEgORGIjEQCQGIjEQiYFIDERiIBIDkRiIxEAkBiIx"
        "EImBSAxEYiASA5EYiMRAJAYiMRCJgUgMRGIgEgORGIjEQCQGIjEQiYFIDERiIBIDkRiIxEAkBiIxEImB"
        "SAxEYiASA5EYiMRAJAYiMRCJgUgMRGIgEgORGIjEQCQGIjEQiYFIDERiIBIDkRiIxEAkBiIxEImBSAxE"
        "YiASA5EYiMRAJAYiMRCJgUgMRGIgEgORGIjEQCQGIjEQiYFIDERiIBIDkRiIxEAkBiIxEImBSAxEYiAS"
        "A5EYiMRAJAYiMRCJgUgMRGIgEgORGIjEQCQGIjEQiYFIDERiIBIDkRiIxEAkBiIxEImBSAxEYiASA5EY"
        "iMRAJAYiMRCJgUgMRGIgEgORGIjEQCQGIjEQiYFIDERiIBIDkRiIxEAkBiLZx2MEfQuoaCoAAAAASUVO"
        "RK5CYII="
    )


@pytest.fixture(scope="module")
def favicon_data_256():
    """256x256 white PNG."""
    return base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAIAAADTED8xAAACvUlEQVR4nO3TMQEAIAzAMMC/5yFjRxMF"
        "fXpn5kDV2w6ATQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0"
        "A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCk"
        "GYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYg"
        "zQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMA"
        "aQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoB"
        "SDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIM"
        "QJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5Bm"
        "ANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0"
        "A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCk"
        "GYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYg"
        "zQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQJoBSDMAaQYgzQCkGYA0A5BmANIMQNoHq+gE"
        "/QPNMGIAAAAASUVORK5CYII="
    )
