from __future__ import annotations

class IllustrationInfo:
    """Information about an illustration in a ZIM archive."""

    def __init__(
        self,
        width: int = 0,
        height: int = 0,
        scale: float = 1.0,
        extra_attributes: dict[str, str] | None = None,
    ) -> None: ...
    @staticmethod
    def from_metadata_item_name(name: str) -> IllustrationInfo: ...
    @property
    def width(self) -> int: ...
    @width.setter
    def width(self, value: int) -> None: ...
    @property
    def height(self) -> int: ...
    @height.setter
    def height(self, value: int) -> None: ...
    @property
    def scale(self) -> float: ...
    @scale.setter
    def scale(self, value: float) -> None: ...
    @property
    def extra_attributes(self) -> dict[str, str]: ...
    @extra_attributes.setter
    def extra_attributes(self, value: dict[str, str]) -> None: ...
    def as_metadata_item_name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
