/* Generated by Cython 0.29.16 */

#ifndef __PYX_HAVE__pyzim
#define __PYX_HAVE__pyzim

#include "Python.h"

#ifndef __PYX_HAVE_API__pyzim

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C std::string string_cy_call_fct(void *, std::string, int *);
__PYX_EXTERN_C zim::Blob blob_cy_call_fct(void *, std::string, int *);
__PYX_EXTERN_C bool bool_cy_call_fct(void *, std::string, int *);
__PYX_EXTERN_C uint64_t int_cy_call_fct(void *, std::string, int *);

#endif /* !__PYX_HAVE_API__pyzim */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpyzim(void);
#else
PyMODINIT_FUNC PyInit_pyzim(void);
#endif

#endif /* !__PYX_HAVE__pyzim */
